### ISSUE TITLE
Would it be possible to select action log directly from the subject?

### ISSUE THREAD

**Issue by yfujis** [brainstem-org/brainstem_support#14]
Hi Peter,

Thank you for your amazing work!
Would it be possible to select action log directly from the subject?
I do linear displacement many times. For now, it seems like the only option is to go to linear displacement from the Action Log page. But it would be helpful to be able to go directly from a specific subject. 

Yuki

**Comment by petersenpeter** [comment]
Hi Yuki

Thanks for the feedback! We have explored this, but unfortunately, in its current implementation, it is a bit difficult to implement action logs in the action form and also inside the subject form. 

We will take your input into account and consider ways to achieve this.
