### ISSUE TITLE
Species not shown in pull down

### ISSUE THREAD

**Issue by yfujis** [brainstem-org/brainstem_support#2]
Hi Peter,

Thank you for the approval of Scotinomys teguina as a species. I realized that when I try to select it for the subjects, it did not show up in the pull down. Is this a bug? or is there a way to select it?

Thanks

**Comment by petersenpeter** [comment]
Hi Yuki

In the subject form, you must tie the subject to a strain. You added a species, and must also submit a strain for it. I realize that you might not be breeding them, but you can only select from strains, not directly from species. You may submit it here: https://www.brainstem.org/private/taxonomies/strain/add/

**Comment by yfujis** [comment]
Hi Peter,

Thank you for the clarification. Since the animals we use are wild-type but bred in a colony here. I submitted a ticket for "Wild-type (NYU)".

Thanks!

**Comment by petersenpeter** [comment]
Hi

Where is the animal from? I will accept the submission, but I would like the name to signify where it is from rather than that is is bred at NYU.

**Comment by yfujis** [comment]
They are originally from Costa Rica. I've just submitted Wild-type (Costa Rica).
Thanks!

**Comment by petersenpeter** [comment]
Hi Yuki

Thanks. I added the description to the strain. I rejected your new submission because the other one already existed in the database.
